kibana:
  service:
    type: LoadBalancer
  elasticsearchHosts: "http://elastic.monitoring.svc.cluster.local:9200"
  extraEnvs:
    - name: "ELASTICSEARCH_USERNAME"
      valueFrom:
        secretKeyRef:
          name: kibana-elastic-secret
          key: username
    - name: "ELASTICSEARCH_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: kibana-elastic-secret
          key: password
